### ISSUE TITLE
Is there a submodule missing ?

### ISSUE THREAD

**Issue by ghost** [myriadrf/front-end-modules#1]
cd front-end-modules
$ git submodule update --recursive
No submodule mapping found in .gitmodules for path 'LimeSDR_PA_LNA/firmware/src'
$

EDIT: I just noticed at the filename in the bin folder LimeSDR-**Sony**.hex, so I'm guessing that is it a closed source problem.

**Comment by 9600** [comment]
Sources were omitted by accident and have now been added.
