### ISSUE TITLE
Datasheets for Sony CXM3624UR and Sony CXGxxxx missing

### ISSUE THREAD

**Issue by xmikos** [myriadrf/front-end-modules#2]
Hello,

I have googled for Sony CXM3624UR and Sony CXGxxxx datasheets and it couldn't be found anywhere on the Internet. This should be open hardware project, could you please provide them?

Also sources for firmware at `LimeSDR_PA_LNA/firmware/src` are missing, there is only some closed binary at `LimeSDR_PA_LNA/firmware/bin/LimeSDR-Sony.hex`. Could you please provide it? Or is this not fully open source / open hardware project?

**Comment by 9600** [comment]
Sony provided us with early access to a limited number of devices and have agreed that we can share the preliminary datasheets, so these have been added to the repo. However, as far as we are aware these devices are not available to buy anywhere just now and so it is not surprising that you cannot find details on the Internet.

As soon as we have any news on availability you can be sure that we will share details. Of course, we have provided the design files and so you're also free to modify the design to use other devices.

The PA module firmware sources were omitted by accident, thanks for pointing this out and these have now been added to the repo!

**Comment by xmikos** [comment]
@9600 Thank you very much for info
